from typing import Optional
from sqlmodel import SQLModel, Field
from sqlalchemy.dialects.sqlite import JSON
from sqlalchemy import Column

# Define the TradeData model with the following columns:
class TradeData(SQLModel, table=True):
    id: int = Field(default=None, primary_key=True)
    uuid: str
    hash: str = Field(unique=True)  # Add unique constraint
    exchange: str
    asset: str
    strategy_name: str
    timeframe: str
    timerange: str

class BacktestData(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    avg_stake_amount: Optional[float] = Field(default=None, nullable=True)
    backtest_best_day: Optional[float] = Field(default=None, nullable=True)
    backtest_best_day_abs: Optional[float] = Field(default=None, nullable=True)
    backtest_days: Optional[int] = Field(default=None, nullable=True)
    backtest_end: Optional[str] = Field(default=None, nullable=True)
    backtest_end_ts: Optional[int] = Field(default=None, nullable=True)
    backtest_hash: Optional[str] = Field(default=None, nullable=True)
    backtest_run_end_ts: Optional[int] = Field(default=None, nullable=True)
    backtest_run_start_ts: Optional[int] = Field(default=None, nullable=True)
    backtest_start: Optional[str] = Field(default=None, nullable=True)
    backtest_start_ts: Optional[int] = Field(default=None, nullable=True)
    backtest_strategy: Optional[str] = Field(default=None, nullable=True)
    backtest_uuid: Optional[str] = Field(default=None, nullable=True)
    backtest_worst_day: Optional[float] = Field(default=None, nullable=True)
    backtest_worst_day_abs: Optional[float] = Field(default=None, nullable=True)
    cagr: Optional[float] = Field(default=None, nullable=True)
    calmar: Optional[float] = Field(default=None, nullable=True)
    canceled_entry_orders: Optional[int] = Field(default=None, nullable=True)
    canceled_trade_entries: Optional[int] = Field(default=None, nullable=True)
    csum_max: Optional[float] = Field(default=None, nullable=True)
    csum_min: Optional[float] = Field(default=None, nullable=True)
    draw_days: Optional[int] = Field(default=None, nullable=True)
    drawdown_end: Optional[str] = Field(default=None, nullable=True)
    drawdown_end_ts: Optional[float] = Field(default=None, nullable=True)
    drawdown_start: Optional[str] = Field(default=None, nullable=True)
    drawdown_start_ts: Optional[float] = Field(default=None, nullable=True)
    draws: Optional[int] = Field(default=None, nullable=True)
    dry_run_wallet: Optional[float] = Field(default=None, nullable=True)
    enable_protections: Optional[bool] = Field(default=None, nullable=True)
    exit_profit_offset: Optional[float] = Field(default=None, nullable=True)
    exit_profit_only: Optional[bool] = Field(default=None, nullable=True)
    expectancy: Optional[float] = Field(default=None, nullable=True)
    expectancy_ratio: Optional[float] = Field(default=None, nullable=True)
    final_balance: Optional[float] = Field(default=None, nullable=True)
    holding_avg: Optional[str] = Field(default=None, nullable=True)
    holding_avg_s: Optional[float] = Field(default=None, nullable=True)
    ignore_roi_if_entry_signal: Optional[bool] = Field(default=None, nullable=True)
    loser_holding_avg: Optional[str] = Field(default=None, nullable=True)
    loser_holding_avg_s: Optional[float] = Field(default=None, nullable=True)
    losing_days: Optional[int] = Field(default=None, nullable=True)
    losses: Optional[int] = Field(default=None, nullable=True)
    market_change: Optional[float] = Field(default=None, nullable=True)
    max_consecutive_losses: Optional[int] = Field(default=None, nullable=True)
    max_consecutive_wins: Optional[int] = Field(default=None, nullable=True)
    max_drawdown_abs: Optional[float] = Field(default=None, nullable=True)
    max_drawdown_account: Optional[float] = Field(default=None, nullable=True)
    max_drawdown_high: Optional[float] = Field(default=None, nullable=True)
    max_drawdown_low: Optional[float] = Field(default=None, nullable=True)
    max_open_trades: Optional[int] = Field(default=None, nullable=True)
    max_open_trades_setting: Optional[int] = Field(default=None, nullable=True)
    max_relative_drawdown: Optional[float] = Field(default=None, nullable=True)
    minimal_roi: Optional[dict] = Field(default=None, sa_column=Column(JSON) )
    pairlist: Optional[list] = Field(default=None, sa_column=Column(JSON))
    profit_factor: Optional[float] = Field(default=None, nullable=True)
    profit_mean: Optional[float] = Field(default=None, nullable=True)
    profit_median: Optional[float] = Field(default=None, nullable=True)
    profit_total: Optional[float] = Field(default=None, nullable=True)
    profit_total_abs: Optional[float] = Field(default=None, nullable=True)
    profit_total_long: Optional[float] = Field(default=None, nullable=True)
    profit_total_long_abs: Optional[float] = Field(default=None, nullable=True)
    profit_total_short: Optional[float] = Field(default=None, nullable=True)
    profit_total_short_abs: Optional[float] = Field(default=None, nullable=True)
    rejected_signals: Optional[int] = Field(default=None, nullable=True)
    replaced_entry_orders: Optional[int] = Field(default=None, nullable=True)
    sharpe: Optional[float] = Field(default=None, nullable=True)
    sortino: Optional[float] = Field(default=None, nullable=True)
    stake_amount: Optional[str] = Field(default=None, nullable=True)
    stake_currency: Optional[str] = Field(default=None, nullable=True)
    stake_currency_decimals: Optional[int] = Field(default=None, nullable=True)
    starting_balance: Optional[float] = Field(default=None, nullable=True)
    stoploss: Optional[float] = Field(default=None, nullable=True)
    strategy_name: Optional[str] = Field(default=None, nullable=True)
    timedout_entry_orders: Optional[int] = Field(default=None, nullable=True)
    timedout_exit_orders: Optional[int] = Field(default=None, nullable=True)
    timeframe: Optional[str] = Field(default=None, nullable=True)
    timeframe_detail: Optional[str] = Field(default=None, nullable=True)
    timerange: Optional[str] = Field(default=None, nullable=True)
    total_trades: Optional[int] = Field(default=None, nullable=True)
    total_volume: Optional[float] = Field(default=None, nullable=True)
    trade_count_long: Optional[int] = Field(default=None, nullable=True)
    trade_count_short: Optional[int] = Field(default=None, nullable=True)
    trades_per_day: Optional[float] = Field(default=None, nullable=True)
    trailing_only_offset_is_reached: Optional[bool] = Field(default=None, nullable=True)
    trailing_stop: Optional[bool] = Field(default=None, nullable=True)
    trailing_stop_positive: Optional[float] = Field(default=None, nullable=True)
    trailing_stop_positive_offset: Optional[float] = Field(default=None, nullable=True)
    use_custom_stoploss: Optional[bool] = Field(default=None, nullable=True)
    use_exit_signal: Optional[bool] = Field(default=None, nullable=True)
    winner_holding_avg: Optional[str] = Field(default=None, nullable=True)
    winner_holding_avg_s: Optional[float] = Field(default=None, nullable=True)
    winning_days: Optional[int] = Field(default=None, nullable=True)
    winrate: Optional[float] = Field(default=None, nullable=True)
    wins: Optional[int] = Field(default=None, nullable=True)
